### ISSUE TITLE
Hent tidsserie-data for begrep fra diff-store

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-reports-bff#115]
Hvordan det ble løst for datasett: https://github.com/Informasjonsforvaltning/fdk-reports-bff/commit/331ce4b73beadd57ec970a40a632bc4fba5a698b

Vil da kunne vise historiske data for begrep og løse https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/658

**Comment by KjerstiSteien** [comment]
@NilsOveTen er dette noe du jobber med nå, eller skal jeg flytte den tilbake til Ready?

**Comment by NilsOveTen** [comment]
> @NilsOveTen er dette noe du jobber med nå, eller skal jeg flytte den tilbake til Ready?

er nok bare jeg som har glemt å lukke :grimacing:

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/fdk-reports-bff/pull/124
