### ISSUE TITLE
FetchFromServiceException

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-reports-bff#138]
FetchFromServiceException: Connection error when attempting to fetch diff store metadata 

> Traceback (most recent call last):
>   File "/app/src/fdk_reports_bff/elasticsearch/datasets.py", line 98, in insert_datasets_timeseries
>     diff_store_metadata = loop.run_until_complete(
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "/app/src/fdk_reports_bff/service/service_requests.py", line 110, in fetch_diff_store_metadata
>     raise FetchFromServiceException(
> fdk_reports_bff.service.utils.FetchFromServiceException
>  Connection error when attempting to fetch diff store metadata from

(fjernet intern url fra trace)

**Comment by NilsOveTen** [comment]
diff-store har blitt arkivert, lukker denne
