### ISSUE TITLE
Timeout annenhver time mot dataset-rdf-query-cache

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-reports-bff#147]
Mulig problemet ligger i query-cache, eller at reports-bff trenger utvidet timeout.
Denne trigges konsekvent annenhver time, men i perioden 29.mars-8.april var det stille.

> fdk_reports_bff.service.utils.FetchFromServiceException
>  Connection error when attempting to fetch diff store metadata from http://fdk-dataset-rdf-query-cache:8080/api/metadata"

**Comment by NilsOveTen** [comment]
diff-store har blitt arkivert, lukker denne
