### ISSUE TITLE
Feil tall for datasett og begrep

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-reports-bff#163]
Rapportsiden viser 1465 datasett i staging, men det er egentlig 1542. Regner med at det er pga en svakhet i sparql-spørringen som brukes for å hente tallene for nå-tilstanden fra sparql-service

ref:
![Screenshot from 2023-08-17 08-12-51](https://github.com/Informasjonsforvaltning/fdk-reports-bff/assets/50194012/4b40f07c-9042-401b-a275-50bc028b20a1)

**Comment by KjerstiSteien** [comment]
@NilsOveTen fortsatt en bug?

**Comment by NilsOveTen** [comment]
> @NilsOveTen fortsatt en bug?

Feilen er ikke synlig, men vi har ikke gjort noe for å fikse det, så vil tippe det vil dukke opp igjen

**Comment by NilsOveTen** [comment]
Ser i tillegg at begrep og api har litt snodige tall i prod, så hele greia hadde nok hatt godt av litt oppmerksomhet

**Comment by NilsOveTen** [comment]
Denne har utvikla seg til å gjelde både datasett og begrep i alle 3 miljøene
