### ISSUE TITLE
BUG: Feil i graf for datasett hvis man velger et filter

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-reports-bff#170]
Grafene inneholder ikke data lenger tilbake enn inneværende år hvis man legger på et filter.
Ufiltrert viser grafen data tilbake tom 2018

Grafen ser ut til å virke fint for de andre datatypene, så dette virker kun å gjelde datasett.

![image](https://github.com/Informasjonsforvaltning/fdk-reports-bff/assets/8625716/0cb8a415-7ad1-4814-839a-0db2628681f1)

**Comment by NilsOveTen** [comment]
diff-store har blitt arkivert, lukker denne
