### ISSUE TITLE
Bug: Feil dato for økning av datasett i staging, demo og prod

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-reports-bff#179]
## Hva feiler?
Grafen over datasett viser en økning på dagens dato. Økningen skjedde egentlig i desember. 

## Ønsket oppførsel:
Ønsker at grafen skal vise riktig tid for økning og reduksjon av data i felles datakatalog. 

## Hvordan gjenskape? 
Gå inn på https://data.norge.no/reports scroll ned til grafen. Sjekk når økningen fra ca 1700 datasett til ca 8300 datasett skjedde.

**Comment by NilsOveTen** [comment]
diff-store har blitt arkivert, lukker denne
