### ISSUE TITLE
Rapportsiden: Filtrering på ukjent (MISSING) returnerer 0 treff

### ISSUE THREAD

**Issue by rannveigskjerve** [Informasjonsforvaltning/fdk-reports-bff#20]
Grunn: MISSING er en verdig som legges til av elasticsearch for dockumenter som mangler et felt, når dette sendes in som parameter blir det ikke gjenkjent

- [ ] legge til exists filter for missing verdier

ser tydelig dette på rapportsiden:
![image](https://user-images.githubusercontent.com/39513382/94783358-dc598c80-03cc-11eb-882f-c223b548b326.png)

**Comment by lillelars** [comment]
Denne ser ut til å fungere korrekt nå. Testet i chrome, i staging. Lukker saken.
