### ISSUE TITLE
Demo: oppdatering av ES data feiler 

### ISSUE THREAD

**Issue by rannveigskjerve** [Informasjonsforvaltning/fdk-reports-bff#26]
Ved et høyt antall ukjente dct:publisher feiler innhenting av data før es ingest

**Comment by valosnah** [comment]
Løst ved å la enhetsregisteret-mock gjøre oppslag mot det ekte enhetsregisteret.

**Comment by shenluna** [comment]
Denne er løst, se kommentar fra valosnah
